#ifndef _GAME_H
#define _GAME_H

enum {
	BLEH_TYPE = 1,
    TANK_OBJECT_TYPE,
	INVINCIBLE_OBJECT_TYPE,
	PROJECTILE_OBJECT_TYPE,
    BULLET_OBJECT_TYPE,
    PICKUP_OBJECT_TYPE,
    RACER_OBJECT_TYPE,
    PLATFORM_OBJ_TYPE,
    CANNON_OBJ_TYPE,
    END_OBJ_TYPE,
    GROUND_OBJ_TYPE,
	SLIP_OBJECT_TYPE ,
	ITEM_OBJECT_TYPE 
};

void HandleCollisions();

#endif
